wechat:
  appId: '${{ secrets.APP_ID }}'
  appSecret: '${{ secrets.APP_SECRET }}'
  userId: '${{ secrets.USER_ID }}'
  templateId: '${{ secrets.TEMPLATE_ID }}'
  weatherKey: "${{ secrets.WEATHER_KEY }}"
  rainbowKey: '${{ secrets.RAINBOW_KEY }}'

  ## 模版使用部分
  nickName: '${{ secrets.NICK_NAME }}'
  userCity: '${{ secrets.USER_CITY }}'
  sinceDate: '${{ secrets.SINCE_DATE }}'
  birthday: '${{ secrets.BIRTHDAY }}'
