name: live
on:
  workflow_dispatch:
  schedule:
    # 代表国际标准时间4点0分，北京时间需要+8小时，代表北京时间中午12点运行
    - cron: '0 10 * * ?'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Replace value in YAML file
        run: |
          yq -i '.wechat.appId="${{ secrets.APP_ID }}"' config/config.yaml
          yq -i '.wechat.appSecret="${{ secrets.APP_SECRET }}"' config/config.yaml
          yq -i '.wechat.userId="${{ secrets.USER_ID }}"' config/config.yaml
          yq -i '.wechat.templateId="${{ secrets.TEMPLATE_ID }}"' config/config.yaml
          yq -i '.wechat.weatherKey="${{ secrets.WEATHER_KEY }}"' config/config.yaml
          yq -i '.wechat.rainbowKey="${{ secrets.RAINBOW_KEY }}"' config/config.yaml
          yq -i '.wechat.nickName="${{ secrets.NICK_NAME }}"' config/config.yaml
          yq -i '.wechat.userCity="${{ secrets.USER_CITY }}"' config/config.yaml
          yq -i '.wechat.sinceDate="${{ secrets.SINCE_DATE }}"' config/config.yaml
          yq -i '.wechat.birthday="${{ secrets.BIRTHDAY }}"' config/config.yaml
      - name: live
        run: |
          python3 main.py
