name: live
on:
  workflow_dispatch:
  schedule:
    # 代表国际标准时间4点0分，北京时间需要+8小时，代表北京时间中午12点运行
    - cron: '0 10 * * ?'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Replace value in YAML file
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          RAINBOW_KEY: ${{ secrets.RAINBOW_KEY }}
          USER_ID: ${{ vars.USER_ID }}
          TEMPLATE_ID: ${{ vars.TEMPLATE_ID }}
          NICK_NAME: ${{ vars.NICK_NAME }}
          USER_CITY: ${{ vars.USER_CITY }}
          SINCE_DATE: ${{ vars.SINCE_DATE }}
          BIRTHDAY: ${{ vars.BIRTHDAY }}
        run: |
          yq -i '.wechat.appId="${{ env.APP_ID }}"' config/config.yaml
          yq -i '.wechat.appSecret="${{ env.APP_SECRET }}"' config/config.yaml
          yq -i '.wechat.userId="${{ env.USER_ID }}"' config/config.yaml
          yq -i '.wechat.templateId="${{ env.TEMPLATE_ID }}"' config/config.yaml
          yq -i '.wechat.weatherKey="${{ env.WEATHER_KEY }}"' config/config.yaml
          yq -i '.wechat.rainbowKey="${{ env.RAINBOW_KEY }}"' config/config.yaml
          yq -i '.wechat.nickName="${{ env.NICK_NAME }}"' config/config.yaml
          yq -i '.wechat.userCity="${{ env.USER_CITY }}"' config/config.yaml
          yq -i '.wechat.sinceDate="${{ env.SINCE_DATE }}"' config/config.yaml
          yq -i '.wechat.birthday="${{ env.BIRTHDAY }}"' config/config.yaml
      - name: View YAML
        run: cat config/config.yaml
      - name: live
        run: |
          python3 main.py
